[phases.setup]
nixPkgs = [
  "php",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.pdo_pgsql",
  "php82Extensions.mbstring",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "php82Extensions.curl",
  "php82Extensions.zip"
]
